theme: jekyll-theme-cayman
title: "Workshop on Deep Learning and Inverse Problems"
description: "NeurIPS 2020 workshop, Friday December 11th or Saturday December 12th, Online"
github:
  is_project_page: false
