theme: jekyll-theme-cayman
title: "Solving inverse problems with deep networks: New architectures, theoretical foundations, and applications"
description: "NeurIPS 2019 workshop, Friday December 13th, 2019, Room West 301-305, Vancouver Convention Center"
github:
  is_project_page: false
